apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: AAA
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: AAA 
  name: AAA
  namespace: test
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: AAA
    weight: 100 
